### PR TITLE
[Don't merge] Sharp compress

### PR DESCRIPTION
**Pull request by BasedMan**
I saw that you wanted to exchange 7zip for SharpCompress and went ahead and implemented it. The new version however is orders of magnitudes slower than the old one. You should try it out for yourself, but I doubt you will be ok with the loss of performance.

### CODE REVIEW

**Comment by Helios747** [comment]
I can't test this because the reason I didn't use SharpCompress in the first place was because I couldn't get their repo to compile without errors. If you got it to compile, could you include the .dll into the external libs folder? On the other hand, if you think this isn't really worth merging, you can just close it.

Depending on how much of a performance hit this is, I might prefer a crappy fast library over a decent slow one, considering that the user will be testing lots of builds. If it's not that bad then having fixed UI feedback on the extraction would be worth it.

**Comment by BasedMan** [comment]
Actually you should be able to test it just fine, I've included SharpCompress as a nuget packet. 
The extraction progress bar is still a bit funky in my opinion, but it seems to be at least approximately correct.

**Comment by Helios747** [comment]
Wait, I forgot that commit https://github.com/aserna3/DolphinBisectTool/commit/37f2caa29973bb7fe3c7cd9893b0ba621e44d24 fixed extraction progress with the current lib. That said, I'm kind of okay with a crappy fast lib over a good slow lib for this purpose, since it's only doing one thing, and can be shoved away to one function that never has to see the light of day >.>

I'll leave this open if you want to pitch an argument for implementing the better (and slower) lib, but for now I'll just take your advice and not merge it.

**Comment by BasedMan** [comment]
I will benchmark the current libs and some other ones and report back with the results.

**Pull request closed without merging**
